/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_MASTER]    Script Date: 6/1/2020 6:47:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_MASTER]
(
	[BATCH_MASTER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_NAME] [varchar](100) NOT NULL,
	[BATCH_DESC] [varchar](200) NOT NULL,
	[BATCH_TYPE] [varchar](50) NOT NULL,
	[LBU_CD] [varchar](10) NOT NULL,
	[LBU_NAME] [varchar](50) NOT NULL,
	[ENTITY_ID] [varchar](50) NOT NULL,
	[ENTITY_NAME] [varchar](100) NOT NULL,
	[CREATED_USER_ID] [varchar](25) NOT NULL,
	[CREATED_DTTM] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [varchar](25) NOT NULL,
	[MODIFIED_DTTM] [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_DETAILS]    Script Date: 6/1/2020 6:47:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_DETAILS]
(
	[BATCH_RUN_ID] [bigint] NOT NULL,
	[BATCH_MASTER_ID] [bigint] NOT NULL,
	[BATCH_DT] [date] NULL,
	[ACCT_PERIOD] [varchar](10) NOT NULL,
	[LBU_START_DTTM] [datetime] NULL,
	[LBU_END_DTTM] [datetime] NULL,
	[GMT_START_DTTM] [datetime] NULL,
	[GMT_END_DTTM] [datetime] NULL,
	[EXECUTION_STATUS] [varchar](10) NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [BATCH_MASTER_ID] ),
	CLUSTERED INDEX
	(
		[BATCH_MASTER_ID] ASC
	)
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_JOB_MASTER]    Script Date: 6/1/2020 6:47:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_AUDIT_JOB_MASTER]
(
	[JOB_MASTER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_MASTER_ID] [bigint] NOT NULL,
	[JOB_NAME] [varchar](255) NOT NULL,
	[JOB_DESC] [varchar](1000) NOT NULL,
	[FOLDER_NAME] [varchar](100) NOT NULL,
	[SSIS_PKG_NAME] [varchar](255) NOT NULL,
	[CREATED_USER_ID] [varchar](25) NOT NULL,
	[CREATED_DTTM] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [varchar](25) NOT NULL,
	[MODIFIED_DTTM] [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_JOB_RUN_DETAILS]    Script Date: 6/1/2020 6:47:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_AUDIT_JOB_RUN_DETAILS]
(
	[JOB_RUN_ID] [bigint] NOT NULL,
	[BATCH_RUN_ID] [bigint] NOT NULL,
	[JOB_MASTER_ID] [bigint] NOT NULL,
	[LBU_START_DTTM] [datetime] NULL,
	[LBU_END_DTTM] [datetime] NULL,
	[GMT_START_DTTM] [datetime] NULL,
	[GMT_END_DTTM] [datetime] NULL,
	[EXECUTION_STATUS] [varchar](10) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [JOB_MASTER_ID] ),
	CLUSTERED INDEX
	(
		[JOB_MASTER_ID] ASC
	)
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_CHECK_ERROR_THRESHOLD]    Script Date: 6/1/2020 6:47:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_BALANCE_CHECK_ERROR_THRESHOLD]
(
	[BAL_CHECK_ERR_THRESHOLD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_MASTER_ID] [bigint] NOT NULL,
	[JOB_MASTER_ID] [bigint] NOT NULL,
	[SRC_TABLE_NAME] [varchar](2000) NULL,
	[SRC_COLUMN_NAME] [varchar](100) NOT NULL,
	[TGT_TABLE_NAME] [varchar](100) NOT NULL,
	[TGT_COLUMN_NAME] [varchar](100) NOT NULL,
	[BAL_NAME] [varchar](100) NOT NULL,
	[ERROR_THRESHOLD] [int] NOT NULL,
	[PCT_OR_VALUE] [varchar](10) NOT NULL,
	[SRC_FILTER_CONDITION] [varchar](2000) NOT NULL,
	[TGT_FILTER_CONDITION] [varchar](2000) NOT NULL,
	[TGT_PRIMARY_KEY] [varchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_CONTROL]    Script Date: 6/1/2020 6:47:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_BALANCE_CONTROL]
(
	[CONTROL_FILE_ID] [bigint] NOT NULL,
	[FILE_NAME] [varchar](100) NOT NULL,
	[BATCH_DT] [date] NOT NULL,
	[SRC_FILE_GEN_DT] [date] NOT NULL,
	[SRC_FILE_GEN_TIME] [time](7) NOT NULL,
	[RECORD_COUNT] [bigint] NOT NULL,
	[TOTAL_CR_AMT] [decimal](18, 2) NULL,
	[TOTAL_DR_AMT] [decimal](18, 2) NULL,
	[TOTAL_AMT] [decimal](18, 2) NULL,
	[TRANSFER_MODE] [varchar](10) NULL,
	[KPI_1] [decimal](18, 2) NULL,
	[KPI_2] [decimal](18, 2) NULL,
	[KPI_3] [decimal](18, 2) NULL,
	[KPI_4] [decimal](18, 2) NULL,
	[KPI_5] [decimal](18, 2) NULL,
	[CHECKSUM_1] [varchar](100) NULL,
	[CHECKSUM_2] [varchar](100) NULL,
	[CHECKSUM_3] [varchar](100) NULL,
	[CHECKSUM_4] [varchar](100) NULL,
	[CHECKSUM_5] [varchar](100) NULL,
	[STAG_JOB_MASTER_ID] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_RUN_DETAILS]    Script Date: 6/1/2020 6:47:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_BALANCE_RUN_DETAILS]
(
	[BAL_RUN_INSTANCE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[JOB_RUN_ID] [bigint] NOT NULL,
	[BAL_CHECK_ERR_THRESHOLD_ID] [bigint] NULL,
	[BAL_NAME] [varchar](100) NOT NULL,
	[SRC_BAL_VALUE] [decimal](16, 2) NULL,
	[TGT_BAL_VALUE] [decimal](16, 2) NULL,
	[ERROR_BAL_VALUE] [decimal](16, 2) NULL,
	[ERROR_PCT_OR_VALUE] [decimal](16, 2) NULL,
	[BAL_STATUS] [varchar](10) NULL,
	[LBU_CREATED_DTTM] [datetime] NULL,
	[GMT_CREATED_DTTM] [datetime] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [JOB_RUN_ID] ),
	CLUSTERED INDEX
	(
		[JOB_RUN_ID] ASC
	)
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_ERROR_LOG]    Script Date: 6/1/2020 6:47:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_ERROR_LOG]
(
	[ERROR_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_RUN_ID] [bigint] NOT NULL,
	[JOB_RUN_ID] [bigint] NOT NULL,
	[ERROR_REF_CD] [bigint] NOT NULL,
	[ERROR_RECORD_PRIMARY_KEY_VALUES] [varchar](1000) NULL,
	[ERROR_DTTM] [datetime] NULL,
	[UPDATED_DTTM] [datetime] NULL,
	[PKG_NAME ] [varchar](255) NULL,
	[ERROR_TASK_NAME ] [varchar](1000) NULL,
	[ERROR_COLUMNS ] [varchar](100) NULL,
	[ERROR_VALUE] [varchar](2000) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [JOB_RUN_ID] ),
	CLUSTERED INDEX
	(
		[BATCH_RUN_ID] ASC,
		[JOB_RUN_ID] ASC
	)
)
GO

/****** Object:  Table [AUDIT_ID].[ETL_ERROR_REFERENCE]    Script Date: 6/1/2020 6:47:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_ERROR_REFERENCE]
(
	[ERROR_REF_CD] [bigint] IDENTITY(1,1) NOT NULL,
	[ERROR_SUMMARY] [varchar](100) NOT NULL,
	[ERROR_DETAIL_DESC] [varchar](1000) NULL,
	[CREATED_USER_ID] [varchar](25) NOT NULL,
	[CREATED_DTTM] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [varchar](25) NOT NULL,
	[MODIFIED_DTTM] [datetime] NOT NULL,
	[IS_ACTIVE_FLG] [char](1) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

/****** Object:  Table [AUDIT_ID].[LBU_TIMEZONE]    Script Date: 6/1/2020 6:47:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[LBU_TIMEZONE]
(
	[TIMEZONE_NAME] [varchar](100) NULL,
	[LBU_NAME] [varchar](30) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_HEADER]    Script Date: 7/10/2020 4:37:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_HEADER]
(

	[BATCH_DT] [date] NOT NULL,
	[START_DTTM] [datetime] NULL,
	[END_DTTM] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


/****** Object:  Table [AUDIT_ID].[ETL_DUPLICATE_CHECK]    Script Date: 7/24/2020 10:37:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_DUPLICATE_CHECK]
(
	[DUP_CHECK_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_MASTER_ID] [bigint] NOT NULL,
	[JOB_MASTER_ID] [bigint] NOT NULL,
	[TABLE_NAME] [varchar](255) NULL,
	[PRIMARY_KEY] [varchar](1000) NULL,
	[FILTER_CONDITION] [varchar](2000) NOT NULL,
	[CREATED_USER_ID] [varchar](25) NULL,
	[CREATED_DTTM] [datetime] NULL,
	[MODIFIED_USER_ID] [varchar](25) NULL,
	[MODIFIED_DTTM] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


/****** Object:  Table [AUDIT_ID].[ETL_REF_VALUE_CHECK]    Script Date: 7/22/2020 8:02:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AUDIT_ID].[ETL_REF_VALUE_CHECK]
(
	[REF_CHECK_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BATCH_MASTER_ID] [bigint] NOT NULL,
	[JOB_MASTER_ID] [bigint] NOT NULL,
	[TABLE_NAME] [varchar](255),
	[COLUMN_NAME] [varchar](1000),
	[PRIMARY_KEY] [varchar](1000),
	[REF_TABLE_NAME] [varchar](2000),
	[REF_COLUMN_NAME] [varchar](1000),
	[REF_COLUMN_VALUES] [varchar](1000),
	[CREATED_USER_ID] [varchar](25) NULL,
	[CREATED_DTTM] [datetime] NULL,
	[MODIFIED_USER_ID] [varchar](25) NULL,
	[MODIFIED_DTTM] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO