/****** Object:  Table [AUDIT_ID].[LBU_TIMEZONE]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[LBU_TIMEZONE]
GO

/****** Object:  Table [AUDIT_ID].[ETL_ERROR_REFERENCE]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_ERROR_REFERENCE]
GO

/****** Object:  Table [AUDIT_ID].[ETL_ERROR_LOG]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_ERROR_LOG]
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_RUN_DETAILS]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_BALANCE_RUN_DETAILS]
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_CONTROL]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_BALANCE_CONTROL]
GO

/****** Object:  Table [AUDIT_ID].[ETL_BALANCE_CHECK_ERROR_THRESHOLD]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_BALANCE_CHECK_ERROR_THRESHOLD]
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_JOB_RUN_DETAILS]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_AUDIT_JOB_RUN_DETAILS]
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_JOB_MASTER]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_AUDIT_JOB_MASTER]
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_DETAILS]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_DETAILS]
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_MASTER]    Script Date: 6/1/2020 6:38:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_MASTER]
GO

/****** Object:  Table [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_HEADER]    Script Date: 7/10/2020 4:37:57 PM ******/
DROP TABLE [AUDIT_ID].[ETL_AUDIT_BATCH_RUN_HEADER]
GO

/****** Object:  Table [AUDIT_ID].[ETL_DUPLICATE_CHECK]    Script Date: 7/24/2020 10:37:38 AM ******/
DROP TABLE [AUDIT_ID].[ETL_DUPLICATE_CHECK]
GO

/****** Object:  Table [AUDIT_ID].[ETL_REF_VALUE_CHECK]    Script Date: 7/22/2020 8:02:59 PM ******/
DROP TABLE [AUDIT_ID].[ETL_REF_VALUE_CHECK]
GO